apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-senetry
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sentry.io/project-slug: statusneo/takein
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
